eclipse-thingweb/playground

playground-assertions/package.json
playground-cli/package.json
playground-core/examples/tds/valid/formOpArrayWithDefaults.json
playground-core/examples/tds/valid/simpleWithDefaults.json
playground-core/index.js
playground-core/package.json
playground-web/package.json
playground-web/util.js

* Added two new examples (former green colored examples enhanced with default values to really pass all validations)
* Changed classification of former valid examples to warning
* Removed `private: true` tag from package infos to prepare publication
* Added additional check for read/writeOnly:
* Warning if `readOnly` and `writeOnly` are true
* Warning if `writeOnly` and `observable` are true
* Warning if `writeOnly` or `readOnly` is true and `op` not set (--> default is `["readproperty", "writeproperty"]`)
* Warning if `writeOnly` or `readOnly` is set and `readproperty` or `writeproperty` contained in `op` array or is the `op` string value
* #130
* #117 
* #116

Issue solving: adapt examples, check read/writeOnly

---

playground-web/util.js

Add the following symbols to the example list, to make their validation results known, even if the background color styling does not work for the respective OS/Browser pair. 
valid -> &check;
warning -> !
fail -> &cross;
Solves #129 
Looks like this:
on Chrome, Windows Firefox
on Linux Firefox and maybe also other browsers

add symbols for example categories

---

.github/workflows/ci-cd.yaml
.github/workflows/gist-backend-ci.yaml
packages/gist_backend/README.md
packages/gist_backend/package.json
packages/gist_backend/real-test.js
packages/gist_backend/test.js

Only trigger testing the gist_backend by really submitting a TD gist (and delete it afterwards) on pushes to the `thingweb/thingweb-playground` repository.
For default CI simply start the backend server and shut it back down if it doesn't throw an error.

Move gist backend CI to separate job

---

packages/assertions/index.js

This PR fixes an issue discovered in https://github.com/w3c/wot-testing/pull/349: In TMs, both the `title` and the `id` fields are optional. This led to problems with the way a `tmName` was generated before, as an `undefined` title could be concatenated with the random number that is being generated, creating a `NaN` value in the process.
The PR solves this problem by introducing an additional check for the title. If the title should be `undefined`, then an `Unnamed TM ` string is used instead. I also applied some minor refactoring in order to avoid too much code duplication.
An alternative would be to generate a UUID for the `tmName` instead, as this would minimize the potential for name clashes. However, this could also be done in a follow-up PR if deemed useful.

Allow for assertion testing of TMs without id and title

---

.github/workflows/ci-cd.yaml

We keep 12.x since the Eclipse server where the web interface is deployed runs 12

Update to newer node versions for ci

---

packages/assertions/assertions-tm/tm-versioning-2.json
packages/assertions/assertions-tm/tmAssertionList.json
packages/core/examples/tms/invalid/optionalWrongLocation.json
packages/core/examples/tms/valid/optional.json
packages/core/examples/tms/valid/version.json
packages/core/index.js
packages/core/shared.js
packages/core/td-schema.json
packages/core/tm-schema.json

This PR is (or will until ready) implementing the following assertions of the td spec:

Assertion fixes for CR transition

---

packages/web/jsonld-vis.js

While working on the related PR for ediTDor, I've realized that there is `toString()` missing.

add missing toString

---

.github/scripts/deploy-web.sh
CONTRIBUTING.md
README.md
package-lock.json
package.json
packages/assertions/README.md
packages/assertions/package.json
packages/cli/README.md
packages/cli/package.json
packages/core/README.md
packages/core/package.json
packages/defaults/README.md
packages/defaults/package.json
packages/json-spell-checker/README.md
packages/json-spell-checker/package.json
packages/td_to_asyncapi/README.md
packages/td_to_asyncapi/package.json
packages/td_to_openAPI/README.md
packages/td_to_openAPI/package.json
packages/web/README.md
packages/web/index.html
packages/web/package.json

After moving to Eclipse, these can be made correct

Update the Thingweb URLs

---

packages/web/index.html
packages/web/script.js
packages/web/style.css
packages/web/util.js

- Removed the clipboard functionality to address the browser support issues
- Share URL text now adapts depending if the document is a TD or a TM
- Introduced a new button that enables users to effortlessly open the generated URL in another playground tab

Changed "share url" pop up functionality

---

.github/workflows/assertionscsv-update.yml

In order to avoid cases such as https://github.com/eclipse-thingweb/playground/actions/runs/5745360467/workflow

ci: fix lerna version for assertions

---

packages/web-new/package-lock.json
packages/web-new/package.json
packages/web-new/src/template.html

This should bring the new AID conversion logic

web: use new node-wot release

---

packages/web-new/src/scripts/console.js
packages/web-new/src/scripts/main.js
packages/web-new/src/scripts/visualize.js
packages/web-new/src/template.html

The console now auto expands when the console is minimized and the user clicks on one of the console options.

Auto-expanding the console when clicking on it

---

packages/web-new/src/scripts/aas.js
packages/web-new/src/scripts/async-api.js
packages/web-new/src/scripts/defaults.js
packages/web-new/src/scripts/editor.js
packages/web-new/src/scripts/examples-menu.js
packages/web-new/src/scripts/json-yaml.js
packages/web-new/src/scripts/jsonld-vis.js
packages/web-new/src/scripts/open-api.js
packages/web-new/src/scripts/save-menu.js
packages/web-new/src/scripts/settings-menu.js
packages/web-new/src/scripts/vega-vis.js
packages/web-new/src/styles/_examples-menu.scss
packages/web-new/src/template.html

- Changed the quick-use button to a simpler, more obvious variation.
- Instead of utilizing an icon that implies import, the button now has the simple text of "use"

Modified quick use button

---

.github/workflows/visual-ci-new.yaml
packages/web-new/playwright.config.js
packages/web-new/tests/test.spec.js

These are the new updated and fixed playwright tests as well as the updated YAML file for GitHub actions

Implement new visual testing for the web-new package

---

.github/workflows/ci-cd.yaml

Ignore old web package from testing and fix node versions

---

.eslintrc.json
packages/web-new/package-lock.json
packages/web-new/package.json
packages/web-new/src/scripts/console.js
packages/web-new/src/scripts/editor.js
packages/web-new/src/scripts/jsonld-vis.js
packages/web-new/src/scripts/save-menu.js
packages/web-new/tests/test.spec.js

- Solved all remaining issues in my scripts, and test that were causing the ESlint test to fail
- Modified the eslinrc.json file to a slightly newer version which accepts the spread operator 
- As well as adding "sourceType": "module"  to the parserOptions to accept "module" scripts
Also @egekorkan  is there a reason to why we are utilizing such an old version (8 / 2017) of ESlint, or should we bump it up to the 2013 or 2014 versions?

Fixed ESlint issues with the web-new package

---

packages/web/netlify.toml

The Lighthouse integration in Netlify defaults to mobile apps. We are adding config to use Desktop https://github.com/netlify/netlify-plugin-lighthouse?tab=readme-ov-file#run-lighthouse-audits-for-desktop

Lighthouse scores based on Desktop

---

packages/web/package-lock.json
packages/web/src/scripts/console.js
packages/web/src/scripts/main.js
packages/web/src/styles/_control-panel.scss
packages/web/src/styles/_examples-menu.scss
packages/web/src/styles/_settings-menu.scss
packages/web/src/styles/styles.scss
packages/web/src/template.html

The required attribution text for Netlify usage has been implemented, along with fixing some other small styling bugs.
Fixes #573

Added attribution for Netlify

---

.eslintrc.json
packages/web/playwright.config.js
packages/web/src/scripts/consent-banner.js
packages/web/src/scripts/main.js
packages/web/src/styles/_settings-menu.scss
packages/web/src/styles/styles.scss
packages/web/src/template.html
packages/web/tests/test.spec.js

Google Analytics, as well as the respective banner for consent management, have been implemented on TD Playground following Eclipse's requirements, while also maintaining the same overall design as the consent banner from the Thingweb website."

Implemented the analytics consent banner for Playground

---

packages/web/tests/test.spec.js

The failing Playwright tests were fixed by updating the Eclipse links  (privacy policy, terms of use, and copyright).

Updated the Eclipse links for the Playwright tests

---

packages/web/src/scripts/console.js
packages/web/src/scripts/editor.js
packages/web/src/scripts/util.js

Checking for `@type` being an array

---

README.md

Adopters Information

---

packages/web/tests/test.spec.js

As we changed the page title in https://github.com/eclipse-thingweb/website/pull/120 , we should adapt the tests here

Adapt Test's expected title
