- WebContent/js/playground.js
now it checks if hrefs are combinable with the base uri if there is base uri
> updated href checking

- WebContent/index.html
- WebContent/js/playground.js
Now there is a warning displayed if enum and const is given at the same time
> checking if interaction exists, checking if enum and const coexist

- README.md
- WebContent/Examples/Bundang/Warning/itemsPropertiesWarning.jsonld
- WebContent/js/playground.js
- WebContent/td-schema-bundang-simple.json
added a new TD that gives warnings
string and arrays are accepted for @type
> Bundang-Example Warning TD

- WebContent/Examples/Bundang/Warning/enumConstWarning.jsonld
- WebContent/js/playground.js
Now warnings light an orange light
> Orange Light

- Scripts/node_modules/ajv/package.json
- Scripts/node_modules/fast-json-stable-stringify/package.json
- Scripts/node_modules/jsonld/package.json
- Scripts/package-lock.json
- WebContent/td-schema-bundang-simple.json
adapting to the issue: https://github.com/w3c/wot-thing-description/issues/185
> add new context string

- AssertionTester/assertionTester.js
- AssertionTester/package.json
you can now output the csv results to a specific location
> added option to output to a desired location

- Scripts/playground.js
This enables the usage of the validator from outside.
> Changed absolute paths to relatives paths

- WebContent/Examples/Valid/coffeeMachine.json
> Coffee Machine Thing Description for Tutorial

- playground-web/style.css
> adapt editor size for large screens

- playground-assertions/package.json
- playground-cli/package.json
- playground-core/package.json
- playground-web/package.json
Filled the fields in the package.jsons
> add fields to packages to be ready for publication

- playground-core/examples/tds/invalid/duplicateSecurityDefinitions.json
- playground-core/index.js
- playground-core/test.js
implements the requirements described in #75
> add check for duplicate security definitions

- playground-web/index.html
- playground-web/script.js
- playground-web/style.css
This PR applies:
* fix Playground CLI link (see #144 )
* change console position from bottom to right column
* add margin for main window content
New style:
4096x2160
2560x1440
1920x1080
> Change console style

- playground-td_to_openAPI/genInteraction.js
- playground-td_to_openAPI/tests/genInteraction.test.js
- playground-web/index.html
add support for convertion of uriVariables to openAPI parameters
> Open api parameters

- packages/core/td-schema-full.json
- packages/core/td-schema.json
> update multiple of definition

- packages/assertions/assertionTests-td.js
- packages/assertions/assertionTests-tm.js
- packages/assertions/index.js
- packages/cli/index.js
- packages/core/index.js
This PR fix issue #236 and does some minor linting
> Fixed batch assertion for folders containing one file bug + minor linting

- packages/assertions/assertions-td/td-context-ns-td10-namespace.json
- packages/assertions/assertions-td/td-context.json
td-context-ns-td10-namespace is also incoming
> Changes to context related assertions

- packages/assertions/assertions-td/td-vocab-exclusiveMaximum--IntegerSchema.json
- packages/assertions/assertions-td/td-vocab-exclusiveMaximum--NumberSchema.json
- packages/assertions/assertions-td/td-vocab-exclusiveMinimum--IntegerSchema.json
- packages/assertions/assertions-td/td-vocab-exclusiveMinimum--NumberSchema.json
- packages/assertions/assertions-td/td-vocab-maxLength--StringSchema.json
- packages/assertions/assertions-td/td-vocab-minLength--StringSchema.json
- packages/assertions/assertions-td/td-vocab-multipleOf--IntegerSchema.json
- packages/assertions/assertions-td/td-vocab-multipleOf--NumberSchema.json
> Fixes to assertion to check multiple levels

- packages/assertions/assertions-td/td-vocab-multipleOf--IntegerSchema.json
Trying to fix possible mistakes for https://github.com/w3c/wot-testing/blob/main/events/2022.06.Online/TD/node-wot/TDs/siemens-dataSchemas.jsonld
> Assertion fixes

- .github/workflows/codeql-analysis.yml
This uses the recommendations from GitHub, nothing fancy. Let's see
> test code analysis

- .github/workflows/ci-cd.yaml
- .github/workflows/visual-ci.yaml
> Conditional Workflows

- packages/assertions/assertionTests-td.js
- packages/assertions/assertionTests-tm.js
- packages/cli/README.md
> Showing id or title in error output

- packages/assertions/assertions-td/td-vocab-contentEncoding--StringSchema.json
- packages/assertions/assertions-td/td-vocab-contentMediaType--StringSchema.json
- packages/assertions/assertions-td/td-vocab-default--DataSchema.json
- packages/assertions/assertions-td/td-vocab-pattern--StringSchema.json
> add else block to dataschema definitions for new assertions

- .gitignore
- packages/web/index.html
- packages/web/style.css
(based on https://github.com/thingweb/thingweb-playground/pull/344)
> Refine styling

- .github/workflows/visual-ci.yaml
Server is using v16 so does not make sense to use node 18 for tests
> Change visual ci to node 16

- packages/core/tests/examples-invalid.test.js
- packages/core/tests/examples-valid.test.js
- packages/core/tests/index.test.js
> add tm tests

- packages/web/index.html
- packages/web/script.js
- packages/web/style.css
- packages/web/vega-vis.js
> make vega visualizations draggable

- packages/web/index.html
- packages/web/script.js
- packages/web/style.css
- packages/web/vega-vis.js
Closes #370. Better to merge after #369.
> Visualizations take up all available space

- packages/web/jsonld-vis.css
> fix graph visualization tips for long values

- packages/core/index.js
> remove unnecessary logs

- packages/web/index.html
- packages/web/jsonld-vis.js
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/script.js
(Partially) going to fix the issue #384
> string truncation with respect to lang direction in jsonld vis

- .gitignore
- packages/cli/index.js
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/tests/index-test.js
- packages/core/index.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/web/package-lock.json
Autofix formatting, implement JUnit test results for TMs and TDs using flag `--junit` from CLI.
See #396
> Junit tests

- packages/web/jsonld-vis.js
Adds compliance with https://github.com/thingweb/thingweb-playground/issues/384#issuecomment-1329330263, closes #384.
> add more extensive way of determining string direction

- packages/assertions/generate-changelog.js
Add no changes indicator in the output and fix a bug that caused the log generator to crash if no output path was given
> Changelog script

- packages/assertions/assertionTests-tm.js
- packages/assertions/assertions-tm/tm-tmRef1.json
Coming from findings at https://github.com/w3c/wot-testing/issues/514
> tm:ref fixes

- packages/defaults/examples/td-with-defaults.json
- packages/defaults/examples/td-without-defaults.json
- packages/defaults/index.js
- packages/defaults/src/definitions.js
- packages/defaults/src/shared.js
- packages/defaults/tests/add.test.js
- packages/defaults/tests/remove.test.js
> Defaults success missing

- packages/assertions/generate-changelog.js
See https://github.com/w3c/wot-testing/pull/517#discussion_r1049303161
> Update generate-changelog.js to add a space before line nb

- packages/td_to_openAPI/mapSecurity.js
- packages/td_to_openAPI/tests/mapSecurity.test.js
> Combo security support

- packages/web/script.js
> include tms for typo check

- packages/web/test.js
> fix throwing literals as exceptions

- packages/core/examples/tds/invalid/usingTM.json
- packages/core/shared.js
> td-tm structure check - keys + values

- packages/json-spell-checker/package-lock.json
When you do `npm i` in the root, this file (and only it) gets changed. Apparently, it is outdated (and has the wrong package name).
> fix package-lock file [json-spell-checker]

- packages/core/examples/tms/valid/extend.json
Extend real tm instead of the unexisting one; add description (and change title).
The changes will be needed for tests related to https://github.com/thingweb/thingweb-playground/pull/451.
> refine tm extend test

- packages/core/examples/tds/valid/usingRecursiveTM.json
- packages/core/examples/tds/warning/unavailableDirectTm.json
- packages/core/examples/tds/warning/unavailableRecursiveTm.json
- packages/core/examples/tms/invalid/unavailableParent.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/shared.js
- packages/core/tests/examples-warning.test.js
Last step of #364.
Closes #364.
> resolve tms using node-wot td-tools

- README.md
Did the following:
- Added more badges and fixed links
- Explained package dependencies
- Restructured where a package goal is explained and where its structure is explained.
> Align Readme

- packages/core/examples/tds/invalid/emptyOpArray.json
- packages/core/td-schema-full.json
- packages/core/td-schema.json
- packages/core/tm-schema.json
Part of https://github.com/w3c/wot-thing-description/issues/1841 to do tests here as well
> Schema update

- packages/web/index.html
The footer had outdated information so this quickly updates it.
> Update year and project name in footer

- packages/web-new/src/scripts/util.js
> Fix openAPI capitilization in new web package

- packages/web-new/src/scripts/util.js
> Remove protocol hardcoding from aid conversion

- packages/web/index.html
- packages/web/script.js
- packages/web/style.css
- Added a new popup that will prompt the user to redirect to the new Playground as well as mentioning the closure of the old Playground on April
> Added popup to link to new Playground

- packages/web-new/tests/test.spec.js
- Modified and fixed the UI test to properly function with the new changes created to the application
- Some parts or whole tests were removed as they are no longer needed in the new UI
Note: The simple test took around 15 to 16 minutes to complete and locally everything ran successfully
> Fixed the UI tests to fit the new changes

- README.md
replicating https://github.com/eclipse-thingweb/.github/pull/7
> Align logo usage

- packages/web-new/package-lock.json
- packages/web-new/package.json
This should adapt the AID conversion to the latest version
> node-wot 8.12 version

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/scripts/util.js
- packages/web/webpack.config.js
Changed from the Node-wot td-tools to the new Thing Web AAS package.
> Changed to new AAS package

- packages/web/src/scripts/main.js
Modified the resizing code, to better explain how it works and specify which values are used to set how much an element should collapse or expand.
> Modified and added new comments for the resizing functionality

- packages/cli/package.json
not sure why it was left there...
> Directory URL fix in CLI Package

- .github/workflows/visual-ci.yaml
> Bump upload artifact action

- .github/workflows/visual-ci.yaml
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/styles/_save-menu.scss
- packages/web/src/styles/styles.scss
All developer dependencies have been updated and any errors caused by the update have been fixed.
> Update developer dependencies
